[package]
name = "k8s"
version = "0.1.0"
edition = "2024"

[dependencies]
kube = { version = "2", features = ["client", "runtime", "derive"] }
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
tokio.workspace = true
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
